CREATE TABLE `titels` (
  `ID` int NOT NULL,
  `DESCRIPTION_EN` varchar(255) NOT NULL,
  `DESCRIPTION_AR` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci